[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://app.getdash.ai"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; frame-src 'self' data:; child-src 'self' data:;"
    Cache-Control = "no-cache, no-store, must-revalidate"


[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 

[[headers]]
  for = "/app/immutable/*" # Matches your _headers file path
  [headers.values]
    Cache-Control = "public, immutable, max-age=31536000"
